{
 "title": "snops metrics dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env_id", "query": { "query": "label_values(env_id)" } },
   {
    "name": "node_key",
    "query": {
     "query": "label_values({env_id=\"$env_id\"},node_key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(snarkos_blocks_transactions_total{env_id=\"$env_id\", node_key=\"$node_key\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1/rate(snarkos_bft_height_total{env_id=\"$env_id\", node_key=\"$node_key\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BFT Connected #",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "snarkos_bft_connected_total{env_id=\"$env_id\"}",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "BPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(snarkos_bft_height_total{env_id=\"$env_id\"}[5m])",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "snarkos_bft_height_total{env_id=\"$env_id\"}",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "5 minute rolling average",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "clamp_min(delta(snarkos_blocks_transactions_total{env_id=\"$env_id\"}[5m]) / 300, 0)",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "TCP Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "snarkos_tcp_tasks_total{env_id=\"$env_id\"}",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "snarkos_bft_height_total{env_id=\"$env_id\", node_key=\"$node_key\"}",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "Router Connected Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "snarkos_router_connected_total{env_id=\"$env_id\"}",
     "legendFormat": "{{node_key}}"
    }
   ]
  },
  {
   "title": "Metrics Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{env_id=\"$env_id\"}",
     "legendFormat": "{{node_key}}"
    }
   ]
  }
 ]
}