---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snops-agents
  labels:
    app: snops-agent
spec:
  replicas: 4
  selector:
    matchLabels:
      app: snops-agent
  template:
    metadata:
      labels:
        app: snops-agent
    spec:
      containers:
        - name: snops-agent
          image: snops-agent
          imagePullPolicy: IfNotPresent
          env:
            - name: SNOPS_ENDPOINT
              value: http://snops-service:1234
            - name: SNOPS_AGENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SNOPS_AGENT_VALIDATOR
              value: "true"
            - name: SNOPS_AGENT_CLIENT
              value: "true"
            - name: AGENT_LABELS
              value: "local"
            - name: SNOPS_AGENT_HEALTH_PORT
              value: "8080"
          ports:
            - containerPort: 5000
            - containerPort: 4130
            - containerPort: 3030
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
