[package]
name = "snot-common"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
futures.workspace = true
lasso.workspace = true
lazy_static.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tarpc.workspace = true
thiserror.workspace = true
tokio.workspace = true
